# Generated by Django 2.0.5 on 2019-11-03 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ensino_cursos', '0002_auto_20191103_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacao', models.CharField(max_length=80, verbose_name='Denominação')),
                ('habilitacao', models.CharField(help_text='Digitar a habilitação do egresso. Ex.: Tecnólogo em Processos Gerenciais, Técnico em Plásticos.', max_length=80, verbose_name='Habilitação')),
                ('quantidade_periodos', models.IntegerField(verbose_name='Quantidade de Períodos')),
                ('nr_vagas', models.IntegerField(verbose_name='Número de Vagas')),
                ('carga_horaria', models.IntegerField(help_text='(Carga horária total do curso, em horas-relógio, excluídos estágios e orientações de TCC).', verbose_name='Carga Horária Total')),
                ('duracao_periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ensino_cursos.DuracaoPeriodo', verbose_name='Duração do Período')),
                ('eixo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ensino_cursos.EixoTecnologico', verbose_name='Eixo Tecnológico')),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ensino_cursos.Modalidade')),
                ('periodicidade_oferta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ensino_cursos.PeriodicidadeOferta', verbose_name='Periodicidade da Oferta')),
                ('situacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ensino_cursos.SituacaoCurso', verbose_name='Situação do Curso')),
                ('tipo_curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ensino_cursos.TipoCurso', verbose_name='Tipo de Curso')),
                ('tipo_oferta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ensino_cursos.TipoOferta', verbose_name='Tipo de Oferta')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ensino_cursos.TurnoFuncionamento', verbose_name='Turno de Funcionamento')),
            ],
        ),
    ]
