# Generated by Django 2.0.5 on 2019-11-03 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ensino_cursos', '0003_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponenteCurricular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacao', models.CharField(max_length=10, verbose_name='Denominação')),
                ('ativo', models.BooleanField(default=True, help_text='Desmarque esta opção quando o Componente Curricular não fizer mais parte da turma.')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacao', models.CharField(max_length=10, verbose_name='Denominação')),
                ('periodo', models.IntegerField(help_text='Digitar o semestre para cursos semestrais e o ano para cursos anuais.', verbose_name='Período')),
            ],
        ),
        migrations.AlterField(
            model_name='curso',
            name='carga_horaria',
            field=models.IntegerField(help_text='Digitar a carga horária total do curso, em horas-relógio, excluídos estágios e orientações de TCC.', verbose_name='Carga Horária Total'),
        ),
        migrations.AddField(
            model_name='turma',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ensino_cursos.Curso'),
        ),
        migrations.AddField(
            model_name='componentecurricular',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ensino_cursos.Turma'),
        ),
    ]
