# Generated by Django 2.0.5 on 2019-11-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensino_cursos', '0004_auto_20191103_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='denominacao',
            field=models.CharField(max_length=30, verbose_name='Denominação'),
        ),
    ]
