# Generated by Django 2.0.5 on 2019-11-03 18:33

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('ensino_cursos', '0006_auto_20191103_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentecurricular',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ensino_cursos.Curso'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='componentecurricular',
            name='turma',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='curso', chained_model_field='curso', on_delete=django.db.models.deletion.CASCADE, to='ensino_cursos.Turma'),
        ),
    ]
