# Generated by Django 2.0.5 on 2019-11-03 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ensino_cursos', '0007_auto_20191103_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentecurricular',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ensino_cursos.Turma'),
        ),
    ]
