# Generated by Django 2.0.5 on 2019-10-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegimeTrabalho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=6, verbose_name='Descrição')),
            ],
            options={
                'verbose_name_plural': 'Regimes de Trabalho',
                'verbose_name': 'Regime de Trabalho',
                'ordering': ['descricao'],
            },
        ),
        migrations.AlterField(
            model_name='titulacao',
            name='descricao',
            field=models.CharField(max_length=15, verbose_name='Descrição'),
        ),
    ]
