# Generated by Django 2.0.5 on 2019-10-28 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0002_auto_20191028_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaConcurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=15, verbose_name='Área')),
                ('nivel', models.IntegerField(verbose_name='Nível')),
                ('area_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pai', to='gp.AreaConcurso', verbose_name='Área Pai')),
            ],
            options={
                'verbose_name_plural': 'Áreas do Concurso',
                'ordering': ['area'],
                'verbose_name': 'Área do Concurso',
            },
        ),
        migrations.CreateModel(
            name='SituacaoFuncional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=15, verbose_name='Descrição')),
            ],
            options={
                'verbose_name_plural': 'Situações Funcionais',
                'ordering': ['descricao'],
                'verbose_name': 'Situação Funcional',
            },
        ),
    ]
