# Generated by Django 2.0.5 on 2019-10-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0003_areaconcurso_situacaofuncional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaconcurso',
            name='area',
            field=models.CharField(max_length=50, verbose_name='Área'),
        ),
    ]
