# Generated by Django 2.0.5 on 2019-10-28 21:44

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import ifrs.validator


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0010_auto_20191027_0109'),
        ('gp', '0004_auto_20191028_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[ifrs.validator.validate_CPF])),
                ('siape', models.CharField(max_length=10, unique=True)),
                ('residencia', models.IntegerField(choices=[(0, 'Já morava em Ibirubá'), (1, 'Mudou-se para Ibirubá em função do concurso'), (2, 'Não mora em Ibirubá')], verbose_name='Residência')),
                ('inicio', models.DateField(verbose_name='Início no Campus')),
                ('fim', models.DateField(blank=True, null=True, verbose_name='Saída do Campus')),
                ('regime_trabalho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gp.RegimeTrabalho', verbose_name='Regime de Trabalho')),
                ('situacao_funcional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gp.SituacaoFuncional', verbose_name='Situação Funcional')),
                ('titulacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gp.Titulacao', verbose_name='Titulação')),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
                'verbose_name_plural': 'Servidores',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
