# Generated by Django 2.0.5 on 2019-10-28 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0005_servidor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='fim',
            field=models.DateField(blank=True, help_text='Último dia que o servidor esteve em efetivo exercício no Campus.', null=True, verbose_name='Saída do Campus'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='inicio',
            field=models.DateField(help_text='Data em que o servidor entrou em efetivo exercício no Campus.', verbose_name='Início no Campus'),
        ),
    ]
