# Generated by Django 2.0.5 on 2019-10-29 00:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_auto_20191028_2348'),
        ('admin', '0002_logentry_remove_auto_add'),
        ('gp', '0009_auto_20191029_0026'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TAE',
            new_name='TecnicoAdministrativo',
        ),
        migrations.AlterField(
            model_name='remuneracao',
            name='descricao',
            field=models.CharField(max_length=5, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='setor',
            name='descricao',
            field=models.CharField(max_length=30, verbose_name='Descrição'),
        ),
    ]
