# Generated by Django 2.0.5 on 2019-10-26 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servidores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servidor',
            options={'ordering': ['user__first_name', 'user__last_name'], 'verbose_name_plural': 'Servidores'},
        ),
        migrations.RemoveField(
            model_name='servidor',
            name='nome',
        ),
        migrations.AddField(
            model_name='servidor',
            name='siape',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servidor',
            name='user',
            field=models.OneToOneField(default=123445, on_delete=django.db.models.deletion.PROTECT, related_name='profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
