# Generated by Django 2.0.5 on 2019-10-27 01:09

from django.db import migrations, models
import ifrs.validator


class Migration(migrations.Migration):

    dependencies = [
        ('servidores', '0003_auto_20191026_2348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servidor',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name_plural': 'Servidores'},
        ),
        migrations.AlterField(
            model_name='servidor',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, validators=[ifrs.validator.validate_CPF]),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='siape',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
